package main

import (
	"ATG/internal/config"
	_ "ATG/internal/logger"
	"ATG/internal/server"
	"flag"
	"fmt"
	"os"
)

const (
	progVersion string = "v2.0.0"
	usage       string = `
App Token Gateway (ATG)
  Authorizes API tokens generated by OIDC-authenticated users

  Options:
    -s, --start-server                             Start HTTP listener
    -c, --config <path/to/config.json>             Use config file at specified path [default: /etc/app-token-gateway.json]
    -t, --template-config                          Write an example configuration file to the path specified by -c
    -h, --help                                     Show this help menu
    -V, --version                                  Show version number

Report bugs to: dev@evsec.net
AppTokenGateway home page: <https://github.com/EvSecDev/AppTokenGateway>
`
)

func main() {
	var startServer bool
	var configPath string
	var templateRequested bool
	var versionRequested bool
	flag.BoolVar(&startServer, "s", false, "")
	flag.BoolVar(&startServer, "start-server", false, "")
	flag.StringVar(&configPath, "c", "/etc/app-token-gateway.json", "")
	flag.StringVar(&configPath, "config", "/etc/app-token-gateway.json", "")
	flag.BoolVar(&templateRequested, "t", false, "")
	flag.BoolVar(&templateRequested, "template-config", false, "")
	flag.BoolVar(&versionRequested, "V", false, "")
	flag.BoolVar(&versionRequested, "version", false, "")
	flag.Usage = func() { fmt.Printf("Usage: %s [OPTIONS]...%s", os.Args[0], usage) }
	flag.Parse()

	if startServer {
		srv, err := server.New(configPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error: %v\n", err)
			os.Exit(1)
		}
		err = srv.SetupHTTP()
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error in HTTP setup: %v\n", err)
			os.Exit(1)
		}
		err = srv.Run()
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error in listener: %v\n", err)
			os.Exit(1)
		}
	} else if templateRequested {
		err := config.CreateTemplate(configPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error: %v\n", err)
			os.Exit(1)
		}
	} else if versionRequested {
		fmt.Println(progVersion)
	} else {
		fmt.Printf("No arguments specified or incorrect argument combination. Use '-h' or '--help' to guide your way.\n")
	}
}
